# Generated by Django 5.1.3 on 2024-11-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200, unique=True)),
                ("telephone", models.CharField(max_length=200, unique=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
